interface_name = "wg-server"
address_cidr = "10.8.0.1/24"
listen_port = 51820
peers = []
nat_enabled = true
server_private_key_b64 = "5sQvg3NkEGrKhBeIuBixkkLKVvlEPvjmcLaLskvFycs="
auto_enroll_dir = "enroll"
