interface_name = "wg-server"
address_cidr = "10.8.0.1/24"
listen_port = 51820
nat_enabled = true
server_private_key_b64 = "xcyD3Tu7UrlM8HgtAWJ0vzfD+S5eb+1IyEZoXrlYFGg="

[[peers]]
public_key_b64 = "NtKxdVNCTRNo9arK8+zB5e6aWqslf0WSLu65Qy2t5S0="
address_cidr = "10.8.0.2/32"
allowed_ips = []
